### ISSUE TITLE
conus.io doesn't redirect to https://conus.io

### ISSUE THREAD

**Issue by zlrth** [conusio/conus#39]

**Comment by zlrth** [comment]
might be a quick fix for @elliottw

**Comment by elliottw** [comment]
did a thing, we'll see if works once changes have propogated acrrosed the interneto-sphere

**Comment by elliottw** [comment]
we'll see

**Comment by zlrth** [comment]
i'll reopen this if `wrap-ssl-redirect` hasn't fixed the problem.
