### ISSUE TITLE
images don't show up on all user-product pages

### ISSUE THREAD

**Issue by elliottw** [conusio/conus#5]
![image](https://user-images.githubusercontent.com/1633097/30083965-81d6e556-925e-11e7-833a-27d9c1da4ee1.png)

http://conus.io/user/elliottw@gmail.com/Water%20rower

**Comment by zlrth** [comment]
oh man this was painful

http://conus.io/user/elliottw@gmail.com/Water%20rower doesn't work, but look at the space after "water rower" in the db:

```
{:id 12, :name "Water rower ", :description "", :askingprice "", :producturl "", :imageurl "/images/927528-conus-image.jpg", :email "elliottw@gmail.com", :timestamp #inst "2017-09-05T21:15:27.000000000-00:00"}```

add a trailing %20 to the url, and it picture and other info should show up.

http://conus.io/user/elliottw@gmail.com/Water%20rower%20

**Comment by zlrth** [comment]
not sure about a fix yet. i'm open to ideas.

**Comment by elliottw** [comment]
jesus. that's ok. we just do some validation on the front end

**Comment by zlrth** [comment]
fixed: https://github.com/conusio/conus/commit/12c17a31cf92a4f2ebd19f8a05334db5c45e9f01
